protocols:
  - kusama
  - polkadot

blockHeights:
  kusama: "kusama_block_height"
  polkadot: "polkadot_block_height"

expressions:
  gbs: "gbs_block_height{{ .protocol }}"
  actual: "protocol_block_height{{ .blockHeight }}"

